logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
spring:
  application:
    name: demo
  r2dbc:
    password: root
    url: r2dbc:mysql://localhost:3306/tech_nova_ai_agent_00?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useCursorFetch=true
    username: root
  redis:
    host: localhost
    port: 6379

#debug: true